name: Autotag & Release
on:
  push:
    branches:
      - main
jobs:
  tag-release:
    runs-on: ubuntu-latest
    name: Tag & Release
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Tag & Release
        uses: pantheon-systems/action-autotag@v1
