name: Autotag & Release
on:
  push:
    branches:
      - main
jobs:
  tag-release:
    runs-on: ubuntu-latest
    name: Tag & Release
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag & Release
        uses: pantheon-systems/action-autotag@v1
